# -*- coding: utf-8 -*-
"""IOT-Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RBD11JFudWDY90FTMbfBc-0uG70RHalZ
"""

!pip install pycryptodome

!pip install Pyrebase4

import pyrebase

import json

import pandas as pd
import math

config = {
  "apiKey": "AIzaSyBdhJzeWAsDCXFE_XR-rmUvZ7OhhvTlgjE",
  "authDomain": "dht11-dfccb.firebaseapp.com",
  "databaseURL": "https://dht11-dfccb-default-rtdb.firebaseio.com",
  "projectId": "dht11-dfccb",
  "storageBucket": "dht11-dfccb.appspot.com",
  "messagingSenderId": "445670544896",
  "appId": "1:445670544896:web:19fa76c158e595a02beae5",
  "measurementId": "G-CTBR1CFT8C"
}
firebase=pyrebase.initialize_app(config)
database=firebase.database()

def HumidityReadings():
    db=database.child("DHT").child("humidity").get()
    l = []
    for i in db.each():
        l.append(i.val())
    return l
def TemperatureReadings():
    db=database.child("DHT").child("temperature").get()
    l = []
    for i in db.each():
        l.append(i.val())
    return l

humidity=[]
humidity=HumidityReadings()
temperature=[]
temperature=TemperatureReadings()
# print(humidity)

df = pd.DataFrame(list(zip(humidity, temperature)),columns =['Humidity', 'Temperature'])

df

def Dew_Point_Calculation(temperature,humidity):
  return temperature-((100-humidity)/5)
print(Dew_Point_Calculation(22,85))

df['Dew point temperature'] = Dew_Point_Calculation(df['Temperature'],df['Humidity'])

df

import matplotlib.pyplot as plt

plt.plot(df["Dew point temperature"],color='r')
plt.xlabel('reading no.')
plt.ylabel('Dew point temperature')
plt.title('Variation in dew point temperature')

average_dew_point = df["Dew point temperature"].mean()
average_dew_point

"""#Notification"""

import pandas as pd
import matplotlib.pyplot as plt
# scatter plot
# df.plot(kind='scatter',
#         x='Temperature',
#         y='Dew point temperature',
#         color='red')
# plt.axhline(y=average_dew_point, color='g', linestyle='-')
# # set the title
# plt.title('ScatterPlot')
df['Temperature'].plot(kind="bar", figsize = (10, 10))
plt.axhline(y=average_dew_point, color='r', linestyle='-',label='notification')
# show the plot
plt.xlabel('reading no.')
plt.ylabel('Dew point temperature')
plt.title('Dew point temperature against threshold for notification')